var data = ["account", "achiever", "acoustics", "act", "action", "activity", "actor", "addition", "adjustment", "advertisement", "advice", "aftermath", "afternoon", "afterthought", "agreement", "air", "airplane", "airport", "alarm", "amount", "amusement", "anger", "angle", "animal ", "answer", "ant", "ants ", "apparatus", "apparel", "apple", "apples ", "appliance", "approval", "arch", "argument", "arithmetic", "arm", "army", "art", "attack", "attempt", "attention", "attraction", "aunt", "authority", "babies ", "baby ", "back", "badge", "bag", "bait", "balance", "ball", "balloon", "balls ", "banana", "band", "base", "baseball", "basin", "basket", "basketball", "bat", "bath", "battle", "bead", "beam", "bean", "bear", "bears ", "beast", "bed", "bedroom", "beds ", "bee", "beef", "beetle", "beggar", "beginner", "behavior", "belief", "believe", "bell", "bells ", "berry", "bike", "bikes ", "bird", "birds ", "birth", "birthday", "bit", "bite", "blade", "blood", "blow", "board", "boat", "boats ", "body", "bomb", "bone", "book", "books ", "boot", "border", "bottle", "boundary", "box", "boy", "boys ", "brain", "brake", "branch", "brass", "bread", "breakfast", "breath", "brick", "bridge", "brother", "brothers ", "brush", "bubble", "bucket", "building", "bulb", "bun", "burn", "burst", "bushes", "business", "butter", "button", "cabbage", "cable", "cactus", "cake", "cakes ", "calculator", "calendar", "camera", "camp", "can", "cannon", "canvas", "cap", "caption", "car ", "card", "care", "carpenter", "carriage", "cars ", "cart", "cast", "cat", "cats ", "cattle", "cause", "cave", "celery", "cellar", "cemetery", "cent", "chain", "chair ", "chairs ", "chalk", "chance", "change", "channel", "cheese", "cherries", "cherry", "chess", "chicken ", "chickens ", "children", "chin", "church", "circle", "clam", "class", "clock", "clocks ", "cloth", "cloud", "clouds ", "clover", "club", "coach", "coal", "coast", "coat", "cobweb", "coil", "collar", "color", "comb", "comfort", "committee", "company", "comparison", "competition", "condition", "connection", "control", "cook", "copper", "copy", "cord", "cork", "corn ", "cough", "country", "cover", "cow", "cows ", "crack", "cracker", "crate", "crayon", "cream", "creator", "creature", "credit", "crib", "crime", "crook", "crow", "crowd", "crown", "crush", "cry", "cub", "cup", "current", "curtain", "curve", "cushion", "dad", "daughter", "day", "death", "debt", "decision", "deer", "degree", "design", "desire", "desk", "destruction", "detail", "development", "digestion", "dime", "dinner", "dinosaurs ", "direction", "dirt", "discovery", "discussion", "disease", "disgust", "distance", "distribution", "division", "dock", "doctor", "dog", "dogs ", "doll", "dolls ", "donkey", "door", "downtown", "drain", "drawer", "dress", "drink", "driving", "drop", "drug", "drum", "duck ", "ducks ", "dust", "ear", "earth", "earthquake", "edge", "education", "effect", "egg", "eggnog", "eggs ", "elbow", "end", "engine", "error", "event", "example", "exchange", "existence", "expansion", "experience", "expert", "eye", "eyes", "face", "fact", "fairies ", "fall", "family", "fan", "fang ", "farm", "farmer ", "father", "father", "faucet", "fear", "feast", "feather", "feeling", "feet", "fiction", "field", "fifth", "fight", "finger", "finger", "fire ", "fireman", "fish", "flag", "flame", "flavor", "flesh", "flight", "flock", "floor", "flower", "flowers ", "fly", "fog", "fold", "food", "foot", "force", "fork", "form", "fowl", "frame", "friction", "friend", "friends ", "frog", "frogs ", "front", "fruit", "fuel", "furniture", "alley", "game", "garden", "gate", "geese", "ghost", "giants ", "giraffe", "girl", "girls ", "glass", "glove", "glue", "goat", "gold", "goldfish", "good-bye ", "goose", "government", "governor", "grade", "grain", "grandfather", "grandmother", "grape", "grass", "grip", "ground", "group", "growth", "guide", "guitar", "gun", "hair", "haircut", "hall", "hammer", "hand", "hands ", "harbor", "harmony", "hat", "hate", "head", "health", "hearing", "heart", "heat", "help", "hen", "hill ", "history", "hobbies", "hole", "holiday", "home ", "honey", "hook", "hope", "horn", "horse", "horses ", "hose", "hospital", "hot", "hour", "house", "houses ", "humor", "hydrant", "ice", "icicle", "idea", "impulse", "income", "increase", "industry", "ink", "insect", "instrument", "insurance", "interest", "invention", "iron", "island", "jail", "jam", "jar", "jeans", "jelly", "jellyfish", "jewel", "join", "joke", "journey", "judge", "juice", "jump", "kettle", "key", "kick", "kiss", "kite", "kitten", "kittens ", "kitty ", "knee", "knife", "knot", "knowledge", "laborer", "lace", "ladybug", "lake", "lamp", "land", "language", "laugh", "lawyer", "lead", "leaf", "learning", "leather", "leg ", "legs", "letter", "letters ", "lettuce", "level", "library", "lift", "light", "limit", "line", "linen", "lip", "liquid", "list", "lizards ", "loaf", "lock", "locket", "look", "loss", "love", "low", "lumber", "lunch", "lunchroom", "machine", "magic", "maid", "mailbox", "man", "manager", "map", "marble", "mark", "market", "mask", "mass", "match", "meal", "measure", "meat", "meeting", "memory", "men", "metal", "mice ", "middle", "milk", "mind", "mine", "minister", "mint", "minute", "mist", "mitten", "mom", "money", "monkey", "month", "moon", "morning", "mother", "motion", "mountain", "mouth", "move", "muscle", "music", "nail", "name", "nation", "neck", "need", "needle", "nerve", "nest ", "net", "news", "night", "noise", "north", "nose", "note", "notebook", "number", "nut", "oatmeal", "observation", "ocean", "offer", "office", "oil", "operation", "opinion", "orange", "oranges ", "order", "organization", "ornament", "oven", "owl", "owner", "page", "pail", "pain", "paint", "pan", "pancake", "paper", "parcel", "parent", "park", "part", "partner", "party", "passenger", "paste", "patch", "payment", "peace", "pear", "pen", "pencil", "person", "pest", "pet", "pets ", "pickle", "picture", "pie", "pies ", "pig", "pigs ", "pin", "pipe", "pizzas ", "place", "plane", "planes ", "plant", "plantation", "plants ", "plastic", "plate", "play", "playground", "pleasure", "plot", "plough", "pocket", "point", "poison", "police", "polish", "pollution", "popcorn", "porter", "position", "pot", "potato", "powder", "power", "price", "print", "prison", "process", "produce", "profit", "property", "prose", "protest", "pull", "pump", "punishment", "purpose", "push", "quarter", "quartz", "queen", "question", "quicksand", "quiet", "quill", "quilt", "quince", "quiver", "rabbit ", "rabbits ", "rail", "railway", "rain", "rainstorm", "rake", "range", "rat", "rate", "ray", "reaction", "reading", "reason", "receipt", "recess", "record", "regret", "relation", "religion", "representative", "request", "respect", "rest", "reward", "rhythm", "rice", "riddle", "rifle", "ring", "rings ", "river", "road", "robin ", "rock", "rod", "roll", "roof", "room", "root", "rose", "route", "rub", "rule", "run", "sack", "sail", "salt", "sand", "scale", "scarecrow", "scarf", "scene", "scent", "school", "science", "scissors", "screw", "sea", "seashore", "seat", "secretary", "seed", "selection", "self", "sense", "servant", "shade", "shake", "shame", "shape", "sheep", "sheet", "shelf", "ship", "shirt", "shock", "shoe", "shoes ", "shop", "show", "side", "sidewalk", "sign", "silk", "silver", "sink", "sister", "sisters ", "size", "skate", "skin", "skirt", "sky", "slave", "sleep", "sleet", "slip", "slope", "smash", "smell", "smile", "smoke", "snail", "snails ", "snake", "snakes ", "sneeze", "snow", "soap", "society", "sock", "soda", "sofa", "son", "song", "songs ", "sort", "sound", "soup", "space", "spade", "spark", "spiders ", "sponge", "spoon", "spot", "spring", "spy", "square", "squirrel", "stage", "stamp", "star", "start", "statement", "station", "steam", "steel", "stem", "step", "stew", "stick", "sticks ", "stitch", "stocking", "stomach", "stone", "stop", "store", "story", "stove", "stranger", "straw", "stream", "street", "stretch", "string", "structure", "substance", "sugar", "suggestion", "suit", "summer", "sun", "support", "surprise", "sweater", "swim", "swing", "system", "table", "tail", "talk", "tank", "taste", "tax", "teaching", "team", "teeth ", "temper", "tendency", "tent", "territory", "test", "texture", "theory", "thing", "things ", "thought", "thread", "thrill", "throat", "throne", "thumb", "thunder", "ticket", "tiger", "time", "tin", "title", "toad", "toe", "toes", "tomatoes ", "tongue", "tooth", "toothbrush", "toothpaste", "top ", "touch", "town", "toy ", "toys ", "trade", "trail", "train", "trains ", "tramp", "transport", "tray", "treatment", "tree", "trees ", "trick", "trip", "trouble", "trousers", "truck", "trucks ", "tub", "turkey", "turn", "twig", "twist", "umbrella", "uncle", "underwear", "unit", "use", "vacation", "value", "van", "vase", "vegetable", "veil", "vein", "verse", "vessel", "vest", "view", "visitor", "voice", "volcano", "volleyball", "voyage", "walk", "wall", "war", "wash", "waste", "watch", "water", "wave", "waves ", "wax", "way", "wealth", "weather", "week", "weight", "wheel", "whip", "whistle", "wilderness", "wind ", "window ", "wine", "wing", "winter", "wire", "wish", "woman", "women", "wood", "wool", "word", "work", "worm", "wound", "wren", "wrench", "wrist", "writer", "writing", "yak", "yam", "yard", "yarn", "year", "yoke", "zebra ", "zephyr", "zinc", "zipper", "zoo"];
var movieData = ["The Shawshank Redemption",
	"The Godfather",
	"The Godfather, Part II",
	"The Dark Knight",
	"Pulp Fiction",
	"The Good, The Bad and The Ugly",
	"12 Angry Men",
	"Schindler's List",
	"The Lord of the Rings: The Return of the King",
	"Fight Club",
	"The Fellowship Of The Ring",
	"Star Wars: Episode V - The Empire Strikes Back",
	"Inception",
	"Forrest Gump",
	"One Flew Over the Cuckoo's Nest",
	"The Lord of the Rings: The Two Towers",
	"Interstellar",
	"Goodfellas",
	"The Matrix",
	"Star Wars: Episode IV - A New Hope",
	"Seven Samurai",
	"City of God",
	"Se7en",
	"The Usual Suspects",
	"The Silence of the Lambs",
	"It's a Wonderful Life",
	"Once Upon a Time in the West",
	"Leon: The Professional",
	"Life Is Beautiful",
	"Casablanca",
	"Raiders of the Lost Ark",
	"American History X",
	"Saving Private Ryan",
	"City Lights",
	"Psycho",
	"Spirited Away",
	"Rear Window",
	"Intouchables",
	"Modern Times",
	"Whiplash",
	"Terminator 2: Judgment Day",
	"Memento",
	"The Green Mile",
	"The Pianist",
	"The Departed",
	"Sunset Boulevard",
	"Apocalypse Now",
	"Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb",
	"Gladiator",
	"Back to the Future",
	"Alien",
	"The Prestige",
	"The Great Dictator",
	"The Lives of Others",
	"The Lion King",
	"Django Unchained",
	"The Dark Knight Rises",
	"Cinema Paradiso",
	"The Shining",
	"Paths of Glory",
	"American Beauty",
	"Wall-E",
	"North by Northwest",
	"Aliens",
	"Citizen Kane",
	"Vertigo",
	"Amelie",
	"M",
	"Das Boot",
	"Grave of the Fireflies",
	"Toy Story 3",
	"Oldboy",
	"Princess Mononoke",
	"Star Wars: Episode VI - Return of the Jedi",
	"Once Upon a Time in America",
	"A Clockwork Orange",
	"Reservoir Dogs",
	"Taxi Driver",
	"Double Indemnity",
	"Braveheart",
	"Requiem for a Dream",
	"To Kill a Mockingbird",
	"Lawrence of Arabia",
	"Witness for the Prosecution",
	"Eternal Sunshine of the Spotless Mind",
	"Full Metal Jacket",
	"Singin' in the Rain",
	"The Sting",
	"Bicycle Thieves",
	"Amadeus",
	"Monty Python and the Holy Grail",
	"Snatch",
	"Rashomon",
	"L.A. Confidential",
	"For a Few Dollars More",
	"2001: A Space Odyssey",
	"The Kid",
	"All About Eve",
	"The Apartment",
	"Some Like It Hot",
	"Inglourious Basterds",
	"Birdman",
	"Indiana Jones and the Last Crusade",
	"The Treasure of the Sierra Madre",
	"The Third Man",
	"A Seperation",
	"Yojimbo",
	"Toy Story",
	"Batman Begins",
	"Metropolis",
	"Like Stars on Earth",
	"Unforgiven",
	"Scarface",
	"Raging Bull",
	"Up",
	"Chinatown",
	"3 Idiots",
	"The Great Escape",
	"Downfall",
	"Boyhood",
	"Die Hard",
	"On the Waterfront",
	"Pan's Labyrinth",
	"Mr. Smith Goes to Washington",
	"The Hunt",
	"Heat",
	"CM101MMXI Fundamentals",
	"Gone Girl",
	"The Bridge on the River Kwai",
	"Good Will Hunting",
	"The Bandit",
	"My Neighbor Totoro",
	"The Seventh Seal",
	"Ikiru",
	"The Gold Rush",
	"The Elephant Man",
	"The Wolf of Wall Street",
	"Ran",
	"Wild Strawberries",
	"Blade Runner",
	"The General",
	"Lock, Stock and Two Smoking Barrels",
	"The Secret in Their Eyes",
	"Casino",
	"Gran Torino",
	"The Big Lebowski",
	"Warrior",
	"Rebecca",
	"V for Vendetta",
	"Howl's Moving Castle",
	"Paint It Yellow",
	"The Deer Hunter",
	"It Happened One Night",
	"Cool Hand Luke",
	"How to Train Your Dragon",
	"Fargo",
	"Judgment at Nuremberg",
	"Trainspotting",
	"Gone with the Wind",
	"Rush",
	"Into the Wild",
	"The Maltese Falcon",
	"A Beautiful Mind",
	"Dial M for Murder",
	"The Sixth Sense",
	"The Wages of Fear",
	"Hotel Rwanda",
	"The Thing",
	"Finding Nemo",
	"Mary and Max",
	"No Country for Old Men",
	"Butch Cassidy and the Sundance Kid",
	"Kill Bill: Vol. 1",
	"Platoon",
	"Life of Brian",
	"Incendies",
	"Guardians of the Galaxy",
	"Dil Chahta Hai",
	"12 Years a Slave",
	"Network",
	"Touch of Evil",
	"Diabolique (1955)",
	"Annie Hall",
	"The Princess Bride",
	"There Will Be Blood",
	"The Grand Budapest Hotel",
	"Stand by Me",
	"Sin City",
	"Ben-Hur",
	"The 400 Blows",
	"Amores Perros",
	"In the Name of the Father",
	"Million Dollar Baby",
	"The Grapes of Wrath",
	"The Wizard of Oz",
	"Hachi: A Dog's Tale",
	"Persona",
	"The Best Years of Our Lives",
	"The Avengers",
	"Nausicaä of the Valley of the Wind",
	"The Bourne Ultimatum",
	"Gandhi",
	"The Imitation Game",
	"Donnie Darko",
	"8 1/2",
	"Gangs of Wasseypur",
	"Strangers on a Train",
	"Infernal Affairs",
	"Stalker",
	"12 Monkeys",
	"Jaws",
	"Shutter Island",
	"X-Men: Days of Future Past",
	"High Noon",
	"Lagaan: Once Upon a Time in India",
	"Notorious",
	"The Terminator",
	"Before Sunrise",
	"The King's Speech",
	"Groundhog Day",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Fanny and Alexander",
	"Ip Man",
	"The Battle of Algiers",
	"Rocky",
	"Dog Day Afternoon",
	"The Night of the Hunter",
	"Monsters, Inc.",
	"La Haine",
	"Memories of Murder",
	"La Strada",
	"Pirates of the Caribbean: The Curse of the Black Pearl",
	"Who's Afraid of Virginia Woolf?",
	"Barry Lyndon",
	"A Fistful of Dollars",
	"Castle in the Sky",
	"The Truman Show",
	"The Big Sleep",
	"The Help",
	"Jurassic Park",
	"Roman Holiday",
	"The Graduate",
	"The Hustler",
	"Papillon",
	"Beauty and the Beast",
	"In the Mood for Love",
	"The Celebration",
	"Prisoners",
	"Rope",
	"Swades: We, the People"
];

var defaultData = [
	"Africa",
	"Agent",
	"Air",
	"Alien",
	"Alps",
	"Amazon",
	"Ambulance",
	"America",
	"Angel",
	"Antarctica",
	"Apple",
	"Arm",
	"Atlantis",
	"Australia",
	"Aztec",
	"Back",
	"Ball",
	"Band",
	"Bank",
	"Bar",
	"Bark",
	"Bat",
	"Battery",
	"Beach",
	"Bear",
	"Beat",
	"Bed",
	"Beijing",
	"Bell",
	"Belt",
	"Berlin",
	"Bermuda",
	"Berry",
	"Bill",
	"Block",
	"Board",
	"Bolt",
	"Bomb",
	"Bond",
	"Boom",
	"Boot",
	"Bottle",
	"Bow",
	"Box",
	"Bridge",
	"Brush",
	"Buck",
	"Buffalo",
	"Bug",
	"Bugle",
	"Button",
	"Calf",
	"Canada",
	"Cap",
	"Capital",
	"Car",
	"Card",
	"Carrot",
	"Casino",
	"Cast",
	"Cat",
	"Cell",
	"Centaur",
	"Center",
	"Chair",
	"Change",
	"Charge",
	"Check",
	"Chest",
	"Chick",
	"China",
	"Chocolate",
	"Church",
	"Circle",
	"Cliff",
	"Cloak",
	"Club",
	"Code",
	"Cold",
	"Comic",
	"Compound",
	"Concert",
	"Conductor",
	"Contract",
	"Cook",
	"Copper",
	"Cotton",
	"Court",
	"Cover",
	"Crane",
	"Crash",
	"Cricket",
	"Cross",
	"Crown",
	"Cycle",
	"Czech",
	"Dance",
	"Date",
	"Day",
	"Death",
	"Deck",
	"Degree",
	"Diamond",
	"Dice",
	"Dinosaur",
	"Disease",
	"Doctor",
	"Dog",
	"Draft",
	"Dragon",
	"Dress",
	"Drill",
	"Drop",
	"Duck",
	"Dwarf",
	"Eagle",
	"Egypt",
	"Embassy",
	"Engine",
	"England",
	"Europe",
	"Eye",
	"Face",
	"Fair",
	"Fall",
	"Fan",
	"Fence",
	"Field",
	"Fighter",
	"Figure",
	"File",
	"Film",
	"Fire",
	"Fish",
	"Flute",
	"Fly",
	"Foot",
	"Force",
	"Forest",
	"Fork",
	"France",
	"Game",
	"Gas",
	"Genius",
	"Germany",
	"Ghost",
	"Giant",
	"Glass",
	"Glove",
	"Gold",
	"Grace",
	"Grass",
	"Greece",
	"Green",
	"Ground",
	"Ham",
	"Hand",
	"Hawk",
	"Head",
	"Heart",
	"Helicopter",
	"Himalayas",
	"Hole",
	"Hollywood",
	"Honey",
	"Hood",
	"Hook",
	"Horn",
	"Horse",
	"Horseshoe",
	"Hospital",
	"Hotel",
	"Ice",
	"Ice Cream",
	"India",
	"Iron",
	"Ivory",
	"Jack",
	"Jam",
	"Jet",
	"Jupiter",
	"Kangaroo",
	"Ketchup",
	"Key",
	"Kid",
	"King",
	"Kiwi",
	"Knife",
	"Knight",
	"Lab",
	"Lap",
	"Laser",
	"Lawyer",
	"Lead",
	"Lemon",
	"Leprechaun",
	"Life",
	"Light",
	"Limousine",
	"Line",
	"Link",
	"Lion",
	"Litter",
	"Loch Ness",
	"Lock",
	"Log",
	"London",
	"Luck",
	"Mail",
	"Mammoth",
	"Maple",
	"Marble",
	"March",
	"Mass",
	"Match",
	"Mercury",
	"Mexico",
	"Microscope",
	"Millionaire",
	"Mine",
	"Mint",
	"Missile",
	"Model",
	"Mole",
	"Moon",
	"Moscow",
	"Mount",
	"Mouse",
	"Mouth",
	"Mug",
	"Nail",
	"Needle",
	"Net",
	"New York",
	"Night",
	"Ninja",
	"Note",
	"Novel",
	"Nurse",
	"Nut",
	"Octopus",
	"Oil",
	"Olive",
	"Olympus",
	"Opera",
	"Orange",
	"Organ",
	"Palm",
	"Pan",
	"Pants",
	"Paper",
	"Parachute",
	"Park",
	"Part",
	"Pass",
	"Paste",
	"Penguin",
	"Phoenix",
	"Piano",
	"Pie",
	"Pilot",
	"Pin",
	"Pipe",
	"Pirate",
	"Pistol",
	"Pit",
	"Pitch",
	"Plane",
	"Plastic",
	"Plate",
	"Platypus",
	"Play",
	"Plot",
	"Point",
	"Poison",
	"Pole",
	"Police",
	"Pool",
	"Port",
	"Post",
	"Pound",
	"Press",
	"Princess",
	"Pumpkin",
	"Pupil",
	"Pyramid",
	"Queen",
	"Rabbit",
	"Racket",
	"Ray",
	"Revolution",
	"Ring",
	"Robin",
	"Robot",
	"Rock",
	"Rome",
	"Root",
	"Rose",
	"Roulette",
	"Round",
	"Row",
	"Ruler",
	"Satellite",
	"Saturn",
	"Scale",
	"School",
	"Scientist",
	"Scorpion",
	"Screen",
	"Scuba Diver",
	"Seal",
	"Server",
	"Shadow",
	"Shakespeare",
	"Shark",
	"Ship",
	"Shoe",
	"Shop",
	"Shot",
	"Sink",
	"Skyscraper",
	"Slip",
	"Slug",
	"Smuggler",
	"Snow",
	"Snowman",
	"Sock",
	"Soldier",
	"Soul",
	"Sound",
	"Space",
	"Spell",
	"Spider",
	"Spike",
	"Spine",
	"Spot",
	"Spring",
	"Spy",
	"Square",
	"Stadium",
	"Staff",
	"Star",
	"State",
	"Stick",
	"Stock",
	"Straw",
	"Stream",
	"Strike",
	"String",
	"Sub",
	"Suit",
	"Superhero",
	"Swing",
	"Switch",
	"Table",
	"Tablet",
	"Tag",
	"Tail",
	"Tap",
	"Teacher",
	"Telescope",
	"Temple",
	"Theater",
	"Thief",
	"Thumb",
	"Tick",
	"Tie",
	"Time",
	"Tokyo",
	"Tooth",
	"Torch",
	"Tower",
	"Track",
	"Train",
	"Triangle",
	"Trip",
	"Trunk",
	"Tube",
	"Turkey",
	"Undertaker",
	"Unicorn",
	"Vacuum",
	"Van",
	"Vet",
	"Wake",
	"Wall",
	"War",
	"Washer",
	"Washington",
	"Watch",
	"Water",
	"Wave",
	"Web",
	"Well",
	"Whale",
	"Whip",
	"Wind",
	"Witch",
	"Worm",
	"Yard"
];

var spanishData = [
	"Aguila",
	"Aguja",
	"Agujero",
	"Aire",
	"Alemania",
	"Algodun",
	"Alianza",
	"Alpes",
	"Ambulancia",
	"America",
	"Angel",
	"Anillo",
	"Antartida",
	"Antorcha",
	"Araoa",
	"Archivo",
	"Arco",
	"Argentina",
	"Articulo",
	"As",
	"Atlantida",
	"Azteca",
	"Baile",
	"Bala",
	"Ballena",
	"Banco",
	"Banda",
	"Baoo",
	"Barco",
	"Barra",
	"Bateria",
	"Berlin",
	"Bermudas",
	"Bicho",
	"Blanco",
	"Bloque",
	"Boca",
	"Bola",
	"Bolsa",
	"Bomba",
	"Bosque",
	"Bota",
	"Botella",
	"Botun",
	"Brazo",
	"Bruja",
	"Caballero",
	"Caballo",
	"Cabeza",
	"Cabina",
	"Cabo",
	"Cactus",
	"Cadena",
	"Caja",
	"Cama",
	"Camara",
	"Cambio",
	"Campana",
	"Campo",
	"Canal",
	"Canguro",
	"Canto",
	"Caoa",
	"Capa",
	"Capital",
	"Caqui",
	"Cara",
	"Caravana",
	"Carga",
	"Carrera",
	"Carro",
	"Carta",
	"Casco",
	"Casino",
	"Caza",
	"Cementerio",
	"Centauro",
	"Centro",
	"Cervantes",
	"Checo",
	"Chocolate",
	"Choque",
	"Chuleta",
	"Cientifico",
	"Cinta",
	"Cinturun",
	"Circulo",
	"Clase",
	"Coche",
	"Cocinero",
	"Coco",
	"Cudigo",
	"Cola",
	"Culera",
	"Columna",
	"Cometa",
	"Compas",
	"Concierto",
	"Conejo",
	"Contrabandista",
	"Copa",
	"Corazun",
	"Corneta",
	"Corona",
	"Corredor",
	"Corriente",
	"Corte",
	"Cresta",
	"Cromo",
	"Cruz",
	"Cuadro",
	"Cuarto",
	"Cubierta",
	"Cubo",
	"Cuchillo",
	"Cuello",
	"Cuerda",
	"Cuerno",
	"Cura",
	"Dama",
	"Delta",
	"Destino",
	"Dia",
	"Diamante",
	"Diana",
	"Diario",
	"Diente",
	"Dinosaurio",
	"Disco",
	"Don",
	"Dragun",
	"Duende",
	"Egipto",
	"Embajada",
	"Emperador",
	"Enano",
	"Enfermedad",
	"Enfermera",
	"Enlace",
	"Escorpiun",
	"Espacio",
	"Espia",
	"Estaciun",
	"Estadio",
	"Estado",
	"Estrella",
	"Estudio",
	"Etiqueta",
	"Europa",
	"Extraterrestre",
	"Falda",
	"Fantasma",
	"Faro",
	"Ficha",
	"Fiesta",
	"Figura",
	"Flauta",
	"Flecha",
	"Foso",
	"Francia",
	"Frente",
	"Fuego",
	"Fuente",
	"Fuerza",
	"Furgoneta",
	"Gancho",
	"Gato",
	"Genio",
	"Gigante",
	"Golfo",
	"Golondrina",
	"Golpe",
	"Goma",
	"Gundola",
	"Gota",
	"Grado",
	"Granada",
	"Grano",
	"Grecia",
	"Grifo",
	"Guante",
	"Guardia",
	"Guerra",
	"Gusano",
	"Helado",
	"Helicuptero",
	"Hielo",
	"Hierba",
	"Hoja",
	"Hollywood",
	"Horca",
	"Hospital",
	"Hotel",
	"Iglesia",
	"Iman",
	"India",
	"Indice",
	"Inglaterra",
	"Italia",
	"Jarra",
	"Judia",
	"Juicio",
	"Kiwi",
	"Ladrun",
	"Lago Ness",
	"Laser",
	"Latigo",
	"Lengua",
	"Leun",
	"Libra",
	"Lima",
	"Limusina",
	"Linea",
	"Lista",
	"Llama",
	"Llave",
	"Lomo",
	"Londres",
	"Luna",
	"Luz",
	"Maestro",
	"Magia",
	"Malta",
	"Mancha",
	"Mando",
	"Manga",
	"Mango",
	"Mano",
	"Manzana",
	"Maoana",
	"Marca",
	"Marcha",
	"Marfil",
	"Masa",
	"Mascara",
	"Mazo",
	"Medico",
	"Mercurio",
	"Mesa",
	"Metro",
	"Mexico",
	"Micro",
	"Microscopio",
	"Mielo",
	"Millonario",
	"Mina",
	"Misil",
	"Modelo",
	"Mudulo",
	"Monitor",
	"Mono",
	"Mortero",
	"Mosc˙",
	"Motor",
	"Muelle",
	"Muerte",
	"Muoeca",
	"Muro",
	"Naranja",
	"Nave",
	"Nieve",
	"Nilo",
	"Ninja",
	"Noche",
	"Nota",
	"Nudo",
	"Nueva York",
	"Obra",
	"Ojo",
	"Ola",
	"Olimpo",
	"Upera",
	"Orden",
	"Urgano",
	"Ornitorrinco",
	"Oro",
	"Oso",
	"Pala",
	"Palma",
	"Pantalla",
	"Papel",
	"Paracaidas",
	"Pase",
	"Paso",
	"Pasta",
	"Pastel",
	"Pavo",
	"Pekin",
	"Pelicula",
	"Pelotun",
	"Pendiente",
	"Perro",
	"Pez",
	"Pico",
	"Pie",
	"Pieza",
	"Pila",
	"Piloto",
	"Pincho",
	"Ping¸ino",
	"Pinta",
	"Pioa",
	"Piramide",
	"Pirata",
	"Pista",
	"Pistola",
	"Placa",
	"Plano",
	"Planta",
	"Platano",
	"Playa",
	"Plomo",
	"Pluma",
	"Policia",
	"Polo",
	"Portada",
	"Portero",
	"Potro",
	"Prensa",
	"Prima",
	"Princesa",
	"Puente",
	"Puerto",
	"Pulpo",
	"Pulso",
	"Punta",
	"Punto",
	"Radio",
	"Rascacielos",
	"Ratun",
	"Rayo",
	"Red",
	"Regla",
	"Reina",
	"Reserva",
	"Revoluciun",
	"Rey",
	"Robot",
	"Rojo",
	"Roma",
	"Ronda",
	"Rosa",
	"Ruleta",
	"Sable",
	"Sa"
];

var frenchData = [
  "abandonné",
  "abandonner",
  "abeille",
  "abîmé",
  "abricot",
  "absent",
  "accepter",
  "accident",
  "accompagner",
  "accord",
  "accoucher",
  "accrocher",
  "acheter",
  "acrobate",
  "adorer",
  "adresse",
  "adroit",
  "adulte",
  "aéroport",
  "affaire",
  "agacer",
  "âge",
  "agent",
  "agir",
  "agiter",
  "agneau",
  "aide",
  "aider",
  "aigle",
  "aiguille",
  "ail",
  "aile",
  "aimer",
  "aîné",
  "air",
  "ajouter",
  "album",
  "aliment",
  "aller bien",
  "aller",
  "allumer",
  "allumette",
  "alphabet",
  "ambulance",
  "amener",
  "ami",
  "amour",
  "ampoule",
  "amusant",
  "amuser",
  "an",
  "ananas",
  "ancien",
  "âne",
  "angle",
  "animal",
  "animaux",
  "année",
  "anniversaire",
  "annoncer",
  "anorak",
  "apercevoir",
  "apparaître",
  "appareil",
  "appartement",
  "appel",
  "appeler",
  "appétit",
  "apporter",
  "apprendre",
  "approcher",
  "appuyer",
  "après",
  "après-midi",
  "aquarium",
  "araignée",
  "arbre",
  "arc",
  "arc-en-ciel",
  "arête",
  "argent",
  "arme",
  "armée",
  "armoire",
  "arracher",
  "arranger",
  "arrêt",
  "arrêter",
  "arrière",
  "arriver",
  "arroser",
  "arrosoir",
  "ascenseur",
  "aspirateur",
  "asseoir",
  "assez",
  "assiette",
  "assis",
  "assurer",
  "attacher",
  "attaquer",
  "atteindre",
  "attendre",
  "attention",
  "atterrir",
  "attraper une maladie",
  "attraper",
  "au delà",
  "au milieu de",
  "au milieu",
  "au",
  "au-delà",
  "au-dessous de",
  "au-dessous",
  "au-dessus de",
  "au-dessus",
  "aujourd’hui",
  "autant",
  "auto",
  "autour de",
  "autour",
  "autre",
  "avaler",
  "avancer",
  "avant",
  "avec",
  "avenir",
  "avion",
  "avis",
  "avoir",
  "bagage",
  "bagarre",
  "bague",
  "baguette",
  "baigner",
  "bâiller",
  "bain",
  "baiser",
  "baisser",
  "balai",
  "balançoire",
  "balayer",
  "balcon",
  "baleine",
  "balle",
  "ballon",
  "banane",
  "banc",
  "bande dessinée",
  "bande",
  "barbe",
  "barboter",
  "barbouillé",
  "barque",
  "barre",
  "barreau",
  "barrer",
  "barrette",
  "bas",
  "bassin",
  "bassine",
  "bateau",
  "bâton",
  "battre",
  "baver",
  "bavoir",
  "beau",
  "beaucoup",
  "bébé",
  "bébés",
  "bec",
  "belle",
  "bercer",
  "besoin",
  "bête",
  "bêtes",
  "bêtise",
  "beurre",
  "biberon",
  "bibliothèque",
  "bicyclette",
  "bien",
  "bientôt",
  "bifteck",
  "bijou",
  "bille",
  "billet",
  "biscuit",
  "bisou",
  "bizarre",
  "blanc",
  "bleu",
  "blond",
  "bœuf",
  "boire",
  "bois",
  "boisson",
  "boîte",
  "bol",
  "bon",
  "bonbon",
  "bondir",
  "bonheur",
  "bonhomme",
  "bonjour",
  "bonne",
  "bonnet",
  "bord",
  "bosse",
  "bosser",
  "botte de foin",
  "botte",
  "bottes",
  "bouche",
  "boucher",
  "boucherie",
  "bouchon",
  "bouder",
  "boue",
  "bouée",
  "bouger",
  "bouillir",
  "boulanger",
  "boulangerie",
  "boule",
  "boulot",
  "bouquet",
  "bourgeon",
  "bousculer",
  "bout",
  "bouteille",
  "boutique",
  "bouton",
  "bracelet",
  "branche",
  "bras",
  "bretelle",
  "bricolage",
  "briller",
  "brosse",
  "brouette",
  "brouillard",
  "bruit",
  "brûler",
  "brun",
  "bûche",
  "buisson",
  "bulles",
  "bureau",
  "bus",
  "cabane",
  "cabinet",
  "caché",
  "cacher",
  "cadeau",
  "cadenas",
  "cadre",
  "café",
  "cage à écureuil",
  "cage",
  "cagoule",
  "cahier",
  "caillou",
  "caisse",
  "calendrier",
  "câlin",
  "câliner",
  "calme",
  "calmer",
  "camarade",
  "caméscope",
  "camion",
  "camp",
  "campagne",
  "camper",
  "canapé",
  "canard",
  "caniveau",
  "canne à pêche",
  "canne",
  "capitaine",
  "caprice",
  "car",
  "caravane",
  "caresse",
  "caresser",
  "carnet",
  "carotte",
  "carreau",
  "carrefour",
  "cartable",
  "carte d’appel : affiche",
  "carte",
  "carton",
  "casier",
  "casque",
  "casquette",
  "cassé",
  "casser",
  "casserole",
  "cassette",
  "catalogue",
  "cauchemar",
  "cause",
  "cave",
  "cédé",
  "cédérom",
  "ceinture",
  "cerceau",
  "céréale",
  "cerf",
  "cerf-volant",
  "cerise",
  "certain",
  "cesser",
  "chaîne",
  "chaise",
  "chaises",
  "chambre",
  "champ",
  "champignon",
  "chance",
  "changeant",
  "changer",
  "chanson",
  "chanter",
  "chapeau",
  "charcuterie",
  "charger",
  "chariot",
  "chasser",
  "chasseur",
  "chat",
  "châtaigne",
  "château",
  "chaud",
  "chauffer",
  "chaussette",
  "chausson",
  "chaussure",
  "chef",
  "chemin",
  "cheminée",
  "chemise",
  "chêne",
  "chenille",
  "cher",
  "chercher",
  "chéri",
  "cheval",
  "cheveu",
  "cheville",
  "chèvre",
  "chez",
  "chien",
  "chiffon",
  "chiffre",
  "chocolat",
  "choisir",
  "choix",
  "chose",
  "chou",
  "chouette",
  "chuchoter",
  "chute",
  "ciel",
  "cigarette",
  "cigogne",
  "cil",
  "cimetière",
  "cinéma",
  "cinq",
  "cirque",
  "ciseaux",
  "citron",
  "citrouille",
  "clair",
  "classe",
  "clé",
  "clémentine",
  "client",
  "clignoter",
  "clin d’œil",
  "cloche",
  "clocher",
  "clou",
  "clown",
  "coccinelle",
  "cochon d’Inde",
  "cochon",
  "cocotte",
  "cœur",
  "coffre",
  "coffret",
  "coiffeur",
  "coin",
  "col",
  "colère",
  "colis-route",
  "collant",
  "colle",
  "coller",
  "collier",
  "colline",
  "colonel",
  "coloriage",
  "colorier",
  "commencer",
  "comparer",
  "comprendre",
  "compte",
  "compter",
  "concombre",
  "conduire",
  "confiance",
  "confiture",
  "confortable",
  "connaître",
  "consoler",
  "consommé",
  "construire",
  "conte",
  "content",
  "continuer",
  "contraire",
  "contre",
  "copain",
  "copier",
  "coq",
  "coquelicot",
  "coquet",
  "coquetier",
  "coquillage",
  "coquille",
  "coquin",
  "corbeau",
  "corbeille",
  "corde",
  "corps",
  "côté",
  "cou",
  "couché",
  "coucher",
  "coude",
  "coudre",
  "couette",
  "couleur",
  "couloir",
  "coup",
  "couper",
  "cour",
  "courant",
  "courir après",
  "courir",
  "couronne",
  "courrier",
  "cours",
  "course",
  "court",
  "cousin",
  "cousine",
  "coussin",
  "couteau",
  "coûter",
  "couver",
  "couvercle",
  "couvert",
  "couverture",
  "couvrir",
  "crabe",
  "cracher",
  "craie",
  "craindre",
  "crapaud",
  "cravate",
  "crayon",
  "crèche",
  "crêpes",
  "creuser",
  "creux",
  "crevette",
  "cri",
  "crier",
  "crochet",
  "crocodile",
  "croire",
  "croix",
  "croquer",
  "croûte",
  "cru",
  "cruel",
  "cube",
  "cueillir",
  "cuillère",
  "cuire",
  "cuisine",
  "cuisiner",
  "cuisinière",
  "cuisse",
  "cuit",
  "culotte",
  "curieux",
  "cuvette",
  "cygne",
  "d’abord",
  "dame",
  "danger",
  "dangereux",
  "dans",
  "danse",
  "danser",
  "dauphin",
  "de",
  "dé",
  "déborder",
  "debout",
  "début",
  "déchirer",
  "décider",
  "décoller",
  "décorer",
  "découpage",
  "découper",
  "découvrir",
  "déçu",
  "dedans",
  "défendre",
  "défiler",
  "dégager",
  "déguisement",
  "déguiser",
  "dehors",
  "déjeuner",
  "délicieux",
  "demain",
  "demander",
  "démarrer",
  "déménager",
  "demi",
  "démolir",
  "dent",
  "dentifrice",
  "dentiste",
  "départ",
  "dépasser",
  "déranger",
  "dernier",
  "derrière",
  "descendre",
  "désobéir",
  "désolé",
  "désoler",
  "désordre",
  "dessert",
  "dessin",
  "dessiner",
  "détester",
  "détruire",
  "deux",
  "deuxième",
  "devant",
  "devenir",
  "deviner",
  "devoir",
  "dictionnaire",
  "dieu",
  "différence",
  "différent",
  "difficile",
  "dimanche",
  "dindon",
  "dîner",
  "dînette",
  "dinosaure",
  "dire",
  "directeur",
  "directrice",
  "discuter",
  "disparaître",
  "distribuer",
  "dix",
  "docteur",
  "doigt",
  "doigts",
  "dollar",
  "domino",
  "donner à manger",
  "donner",
  "dormir",
  "dos",
  "dossier",
  "douche",
  "doucher",
  "douillet",
  "doute",
  "doux",
  "drap",
  "drapeau",
  "droit",
  "droite",
  "drôle",
  "du",
  "dur",
  "eau",
  "écarter",
  "échanger",
  "échapper",
  "écharpe",
  "échasse",
  "échasses",
  "échelle",
  "éclabousser",
  "éclair",
  "éclairer",
  "éclater",
  "école",
  "écorce",
  "écouter",
  "écran",
  "écraser",
  "écrire",
  "écriture",
  "écureuil",
  "effacer",
  "effet",
  "effort",
  "effrayé",
  "égal",
  "église",
  "élastique",
  "électrique",
  "éléphant",
  "élève",
  "élever",
  "éloigner",
  "embouteillage",
  "embrasser",
  "emmener",
  "empêcher",
  "emporter",
  "en argent",
  "en avance",
  "en bas de",
  "en bas",
  "en face",
  "en haut de",
  "en haut",
  "en or",
  "en rang",
  "en retard",
  "enceinte",
  "encore",
  "endive",
  "endroit",
  "énervé",
  "enfant",
  "enfermer",
  "enfiler",
  "enfoncer",
  "engin",
  "enlever",
  "ennemi",
  "ensemble",
  "entendre",
  "enterrer",
  "entier",
  "entonnoir",
  "entourer",
  "entrée",
  "entrer",
  "enveloppe",
  "envie",
  "envoyer",
  "épais",
  "épaule",
  "épée",
  "épingle",
  "éplucher",
  "épluchure",
  "éponge",
  "époque",
  "équipe",
  "erreur",
  "escabeau",
  "escalader",
  "escalier",
  "escargot",
  "espèce",
  "espérer",
  "esprit",
  "essayer",
  "essence",
  "essuyer",
  "étagère",
  "étaler",
  "étang",
  "état",
  "été",
  "éteindre",
  "éternuer",
  "étiquette",
  "étoile",
  "étrange",
  "être",
  "étroit",
  "étude",
  "étudier",
  "évier",
  "éviter",
  "excuser",
  "exemple",
  "exister",
  "expliquer",
  "extérieur",
  "fabriquer",
  "face",
  "facile",
  "façon",
  "facteur",
  "faim",
  "faire beau",
  "faire boire",
  "faire peur",
  "faire",
  "fait",
  "falloir",
  "famille",
  "farce",
  "farine",
  "fatigue",
  "faute",
  "fauteuil",
  "faux",
  "fée",
  "femme",
  "fenêtre",
  "fer à repasser",
  "ferme",
  "fermer",
  "fermier",
  "fesse",
  "fête",
  "feu",
  "feuille",
  "feutre",
  "fève",
  "ficelle",
  "fièvre",
  "figure",
  "fil",
  "filer",
  "filet",
  "fille",
  "film",
  "fils",
  "fin",
  "finir",
  "flamme",
  "flaque",
  "flèche",
  "fleur",
  "fleuriste",
  "flic",
  "flocon",
  "flotter",
  "foin",
  "foire",
  "fois",
  "foncé",
  "fond",
  "fontaine",
  "force",
  "forêt",
  "forme : carré",
  "forme",
  "fort",
  "fou",
  "fouiller",
  "four",
  "fourchette",
  "fourmi",
  "foutre",
  "fraise",
  "framboise",
  "français",
  "frange",
  "frapper",
  "frein",
  "frère",
  "frite",
  "froid",
  "fromage",
  "front",
  "frotter",
  "fruit",
  "fumée",
  "fumer",
  "fusée",
  "fusil",
  "gagner",
  "galette",
  "galoper",
  "gant",
  "garage",
  "garçon",
  "garde",
  "garder",
  "gardien",
  "gare",
  "garer",
  "gars",
  "gâteau",
  "gauche",
  "géant",
  "gelé",
  "geler",
  "gêner",
  "général",
  "genou",
  "genre",
  "gens",
  "gentil",
  "geste",
  "girafe",
  "glace",
  "glaçon",
  "glisser",
  "gobelet",
  "gomme",
  "gonfler",
  "gorge",
  "gosse",
  "gourde",
  "gourmand",
  "goût",
  "goûter",
  "goutte",
  "gouttes",
  "gouvernement",
  "grain",
  "graine",
  "graines",
  "grand",
  "grandir",
  "grand-mère",
  "grand-parent",
  "grand-père",
  "gratter",
  "grave",
  "grenouille",
  "griffe",
  "griffer",
  "grignoter",
  "griller",
  "grimace",
  "grimper",
  "gris",
  "gronder",
  "gros",
  "grotte",
  "groupe",
  "groupé",
  "grue",
  "guêpe",
  "guéri",
  "guérir",
  "guerre",
  "guetter",
  "gueule",
  "guirlande",
  "gymnastique",
  "habit",
  "habiter",
  "habitude",
  "hamster",
  "hanche",
  "handicapé",
  "haricot",
  "haut",
  "hélicoptère",
  "herbe",
  "hérisson",
  "hésiter",
  "heure des mamans",
  "heure",
  "heureux",
  "hibou",
  "hier",
  "hippopotame",
  "hirondelle",
  "histoire",
  "hiver",
  "homme",
  "honneur",
  "hôpital",
  "horloge",
  "hôtel",
  "huile",
  "huit",
  "humain",
  "humeur",
  "humide",
  "hurler",
  "ici",
  "idée",
  "ignorer",
  "île",
  "image",
  "imaginer",
  "imiter",
  "immeuble",
  "immobile",
  "important",
  "importer",
  "impossible",
  "impression",
  "incendie",
  "infirmier",
  "infirmière",
  "inonder",
  "inquiéter",
  "insecte",
  "inséparable",
  "instable",
  "installer",
  "instant",
  "instrument",
  "intéressant",
  "intéresser",
  "intérêt",
  "intérieur",
  "intrus",
  "invitation",
  "inviter",
  "jaloux",
  "jamais",
  "jambe",
  "jambes",
  "jambon",
  "jardin",
  "jardiner",
  "jaune",
  "jean",
  "jeter",
  "jeu",
  "jeudi",
  "jeune",
  "joie",
  "joli",
  "jongler",
  "jonquille",
  "joue",
  "jouer",
  "jouet",
  "jour",
  "journal",
  "journaux",
  "journée",
  "joyeux",
  "jumeau",
  "jumelles",
  "jupe",
  "jurer",
  "jus",
  "juste",
  "kangourou",
  "kiwi",
  "là",
  "lac",
  "lacer",
  "lacet",
  "lâcher",
  "laine",
  "laisse",
  "laisser",
  "lait",
  "lame",
  "lampe",
  "lancer",
  "langue",
  "lapin",
  "large",
  "larme",
  "lavabo",
  "lave-linge",
  "laver",
  "lécher",
  "lecture",
  "léger",
  "légume",
  "lent",
  "lessive",
  "lettre",
  "lever",
  "lèvre",
  "lèvres",
  "lézard",
  "libre",
  "lieu",
  "ligne",
  "linge",
  "lion",
  "liquide",
  "lire",
  "lisse",
  "liste",
  "lit",
  "litre",
  "livre",
  "loin de",
  "loin",
  "long",
  "louche",
  "loup",
  "loupe",
  "lourd",
  "luge",
  "lumière",
  "lundi",
  "lune",
  "lunettes",
  "lutin",
  "machine",
  "madame",
  "magasin",
  "magazine",
  "magicien",
  "magie",
  "magnétoscope",
  "maigre",
  "maillot",
  "main",
  "mains",
  "maintenant",
  "maintenir",
  "maison",
  "maître",
  "maîtresse",
  "mal",
  "malade",
  "maladroit",
  "maman",
  "manche",
  "manège",
  "manger",
  "manière",
  "manquer",
  "manteau",
  "maquillage",
  "maquiller",
  "marchand",
  "marche",
  "marcher à quatre pattes",
  "marcher sur",
  "marcher",
  "mardi",
  "mare",
  "marguerite",
  "mari",
  "mariage",
  "marier",
  "marin",
  "marionnette",
  "marron",
  "marteau",
  "masque",
  "matelas",
  "maternelle",
  "matin",
  "mauvais",
  "méchant",
  "médecin",
  "médicament",
  "meilleur",
  "mélanger",
  "melon",
  "même",
  "ménage",
  "mener",
  "mensonge",
  "mentir",
  "menton",
  "mer",
  "merci",
  "mercredi",
  "merde",
  "mère",
  "mesurer",
  "métal",
  "mètre",
  "mettre du temps",
  "mettre",
  "meuble",
  "micro",
  "midi",
  "mie",
  "miel",
  "mieux",
  "milieu",
  "million",
  "mince",
  "mine",
  "minuit",
  "minute",
  "mixer",
  "modèle",
  "moineau",
  "moins",
  "mois",
  "moitié",
  "moment",
  "monde",
  "monnaie",
  "monsieur",
  "montagne",
  "monter",
  "montre",
  "montrer",
  "monument",
  "morceau de pain",
  "morceau",
  "mordre",
  "mort",
  "mot",
  "moteur",
  "moto",
  "mouche",
  "mouchoir",
  "mouette",
  "moufle",
  "mouillé",
  "mouiller",
  "moule",
  "moulin",
  "mourir",
  "mousse",
  "moustache",
  "moustique",
  "mouton",
  "mouvement",
  "moyen",
  "muet",
  "muguet",
  "multicolore",
  "mur d’escalade",
  "mur",
  "mûr",
  "mûre",
  "muscle",
  "musique",
  "nager",
  "naître",
  "nappe",
  "navet",
  "navire",
  "ne pas oublier",
  "né",
  "neige",
  "neiger",
  "nettoyer",
  "neuf",
  "nez",
  "nid",
  "Noël",
  "nœud",
  "noir",
  "noisette",
  "noix",
  "nom",
  "nombre",
  "nourrir",
  "nourriture",
  "nouveau",
  "noyau",
  "nu",
  "nuage",
  "nuageux",
  "nuit",
  "numéro",
  "obéir",
  "objet",
  "obliger",
  "occuper",
  "odeur",
  "œil",
  "œuf",
  "offrir",
  "ogre",
  "oie",
  "oignon",
  "oiseau",
  "ombre",
  "oncle",
  "ongle",
  "or",
  "orage",
  "orange",
  "orchestre",
  "ordinateur",
  "ordonnance",
  "ordre",
  "oreille",
  "oreiller",
  "os",
  "oser",
  "oublier",
  "ouragan",
  "ours",
  "outil",
  "ouvrier",
  "ouvrir un livre",
  "ouvrir",
  "page",
  "paille",
  "pain",
  "paire",
  "paix",
  "palais",
  "pâle",
  "pamplemousse",
  "panda",
  "panier",
  "panne",
  "panneau",
  "pansement",
  "pantalon",
  "panthère",
  "papa",
  "papier",
  "papillon",
  "pâquerette",
  "paquet",
  "paraître",
  "parapluie",
  "parasol",
  "parc",
  "parcours",
  "pardon",
  "pareil",
  "parent",
  "parfum",
  "parking",
  "parler",
  "parole",
  "part",
  "partager",
  "partie",
  "partir",
  "pas",
  "passage",
  "passé",
  "passer",
  "passerelle",
  "patauger",
  "pâte à modeler",
  "pâte",
  "pâtes",
  "patient",
  "pâtisserie",
  "patron",
  "patte",
  "pauvre",
  "payer",
  "pays",
  "paysage",
  "peau",
  "pêche",
  "pêcheur",
  "pédale",
  "pédaler",
  "peigne",
  "peindre",
  "peine",
  "peinture",
  "pelle",
  "peluche",
  "pendule",
  "pensée",
  "penser",
  "pente",
  "percer",
  "perdre",
  "père",
  "perle",
  "permettre",
  "perroquet",
  "persil",
  "personne",
  "peser",
  "petit pois",
  "petit",
  "petite-fille",
  "petit-enfant",
  "petit-fils",
  "peu",
  "peuple",
  "peur",
  "pharmacie",
  "pharmacien",
  "phoque",
  "photo",
  "photographier",
  "pièce",
  "pied",
  "pieds",
  "pierre",
  "pigeon",
  "pile",
  "pilote",
  "pin",
  "pinceau",
  "pion",
  "pique-niquer",
  "piquer",
  "piqûre",
  "piscine",
  "placard",
  "place",
  "plafond",
  "plage",
  "plaire",
  "plaisir",
  "plan",
  "planche",
  "plante",
  "planter",
  "plat",
  "plateau",
  "plâtre",
  "plein",
  "pleurer",
  "pleuvoir",
  "pli",
  "pliage",
  "plier",
  "plongeoir",
  "plonger",
  "pluie",
  "plume",
  "plus",
  "pluvieux",
  "pneu",
  "poche",
  "poêle",
  "poignet",
  "poing",
  "point",
  "pointe",
  "pointu",
  "poire",
  "poireau",
  "poison",
  "poisson",
  "poli",
  "police",
  "policier",
  "pomme de terre",
  "pomme",
  "pompe",
  "pompier",
  "poney",
  "pont de singe",
  "pont",
  "port",
  "porte",
  "portemanteau",
  "porter",
  "portière",
  "poser",
  "possible",
  "poste",
  "poster",
  "pot",
  "potage",
  "poubelle",
  "pouce",
  "pouf",
  "poule",
  "poulet",
  "poupée",
  "poursuivre",
  "pousser",
  "poussette",
  "poussière",
  "poussin",
  "poutre d’équilibre",
  "pouvoir",
  "prairie",
  "préau",
  "préférer",
  "premier",
  "prendre",
  "prénom",
  "préparer",
  "près de",
  "près",
  "présence",
  "présent",
  "présenter",
  "président",
  "presque",
  "presser",
  "prêt",
  "prêter",
  "prévenir",
  "prier",
  "prince",
  "princesse",
  "prises",
  "prison",
  "priver",
  "prix",
  "problème",
  "prochain",
  "professeur",
  "profond",
  "promenade",
  "promettre",
  "propos",
  "proposer",
  "propre",
  "protéger",
  "prudent",
  "prune",
  "puis",
  "pull-over",
  "punir",
  "purée",
  "putain",
  "puzzle",
  "pyjama",
  "quai",
  "quartier",
  "quatre",
  "question",
  "queue",
  "quitter",
  "quoi",
  "raconter",
  "radiateur",
  "radio",
  "radis",
  "raisin",
  "raison",
  "ramasser",
  "ramener",
  "ramer",
  "rampe",
  "ramper",
  "rangée",
  "ranger",
  "râpe",
  "râper",
  "rapide",
  "rappeler",
  "rapport",
  "raquette",
  "rasoir",
  "rat",
  "râteau",
  "rater",
  "rayon",
  "rayure",
  "recette",
  "recevoir",
  "réciter",
  "recommencer",
  "reconnaître",
  "recoudre",
  "récréation",
  "reculer",
  "réfléchir",
  "réfrigérateur",
  "refuser",
  "regard",
  "regarder",
  "reine",
  "rejoindre",
  "remarquer",
  "remercier",
  "remettre",
  "remonter",
  "remplacer",
  "remplir",
  "remuer",
  "renard",
  "rencontrer",
  "rendre",
  "rentrée",
  "rentrer",
  "renverser",
  "réparer",
  "repas",
  "repasser",
  "répéter",
  "répondre",
  "réponse",
  "reposer",
  "reprendre",
  "requin",
  "respirer",
  "ressembler à",
  "ressembler",
  "restaurant",
  "reste",
  "rester",
  "retard",
  "retarder",
  "retenir",
  "retirer",
  "retour",
  "retourner",
  "retrouver",
  "réussir",
  "rêve",
  "réveil",
  "réveiller",
  "revenir",
  "rêver",
  "revoir",
  "rhinocéros",
  "riche",
  "rideau",
  "rire",
  "risquer",
  "rivière des crocodiles",
  "rivière",
  "riz",
  "robe",
  "robinet",
  "rocher",
  "roi",
  "rond",
  "rondelle",
  "ronfler",
  "ronger",
  "rosé",
  "roue",
  "rouge",
  "roulade",
  "rouleau",
  "rouler",
  "route",
  "roux",
  "ruban",
  "rue",
  "rugueux",
  "s’abriter",
  "s’accrocher",
  "s’agiter",
  "s’allonger",
  "s’amuser",
  "s’appeler",
  "s’appuyer",
  "s’arrêter",
  "s’asseoir",
  "s’échapper",
  "s’écorcher",
  "s’éloigner",
  "s’embrasser",
  "s’endormir",
  "s’ennuyer",
  "s’envoler",
  "s’excuser",
  "s’habiller",
  "s’imaginer",
  "s’installer",
  "s’occuper de",
  "s’ouvrir",
  "sable",
  "sac en plastique",
  "sac",
  "sage",
  "saigner",
  "saison",
  "salade",
  "saladier",
  "sale",
  "salle",
  "saluer",
  "salut",
  "samedi",
  "sang",
  "santé",
  "sapin",
  "sardine",
  "saut",
  "sauter",
  "sauver",
  "savoir",
  "savon",
  "scène",
  "scie",
  "se bagarrer",
  "se baigner",
  "se baisser",
  "se balancer",
  "se battre",
  "se blesser",
  "se blottir",
  "se brûler",
  "se cacher",
  "se changer",
  "se chausser",
  "se cogner",
  "se coiffer",
  "se coucher",
  "se couvrir",
  "se croiser",
  "se dégonfler",
  "se déguiser",
  "se dépêcher",
  "se déshabiller",
  "se détester",
  "se disputer",
  "se doucher",
  "se fâcher",
  "se faner",
  "se garer",
  "se gratter",
  "se laver",
  "se lever",
  "se maquiller",
  "se marier",
  "se mettre debout",
  "se moquer",
  "se moucher",
  "se mouiller",
  "se noyer",
  "se pencher",
  "se percher",
  "se perdre",
  "se pincer",
  "se plaindre",
  "se poser",
  "se presser",
  "se promener",
  "se protéger",
  "se quitter",
  "se rappeler",
  "se raser",
  "se réchauffer",
  "se régaler",
  "se reposer",
  "se retourner",
  "se réveiller",
  "se salir",
  "se sauver",
  "se sécher",
  "se serrer",
  "se servir",
  "se taire",
  "se toucher",
  "se tromper",
  "se trouver",
  "seau",
  "sec",
  "sécher",
  "seconde",
  "secouer",
  "secret",
  "sécurité",
  "seigneur",
  "sel",
  "semaine",
  "sembler",
  "semelle",
  "sens",
  "sentiment",
  "sentir",
  "séparer",
  "sept",
  "sérieux",
  "serpent",
  "serré",
  "serrer",
  "serrure",
  "service",
  "serviette",
  "servir",
  "seul",
  "shampoing",
  "siècle",
  "siège",
  "sieste",
  "siffler",
  "sifflet",
  "signe",
  "silence",
  "simple",
  "singe",
  "situation",
  "six",
  "ski",
  "sœur",
  "soif",
  "soigner",
  "soir",
  "soirée",
  "sol",
  "soldat",
  "sole",
  "soleil",
  "solide",
  "sombre",
  "sommeil",
  "sommet",
  "sonner",
  "sonnette",
  "sorcière",
  "sorte",
  "sortie",
  "sortir",
  "souffler",
  "souffrir",
  "souhaiter",
  "soulever",
  "souligner",
  "soupe",
  "souple",
  "sourcil",
  "sourd",
  "sourire",
  "souris",
  "sous",
  "souvenir",
  "souvent",
  "spectacle",
  "sport",
  "square",
  "squelette",
  "stylo",
  "sucer",
  "sucre",
  "suffire",
  "suite",
  "suivant",
  "suivre",
  "sujet",
  "super",
  "sur",
  "surprise",
  "surveiller",
  "table",
  "tableau",
  "tablier",
  "tabouret",
  "tache",
  "taille",
  "taille-crayon",
  "tailler",
  "taire",
  "talon",
  "tambour",
  "tampon",
  "taper sur",
  "taper",
  "tapis",
  "tard",
  "tarte",
  "tartine",
  "tas",
  "tasse",
  "tâter",
  "taupe",
  "télécommande",
  "téléphone",
  "téléphoner",
  "télévision",
  "tempête",
  "temps",
  "tendre",
  "tenir",
  "tente",
  "tenter",
  "terminer",
  "terrain",
  "terre",
  "terrible",
  "terrier",
  "tête",
  "téter",
  "thé",
  "thermomètre",
  "ticket",
  "tige",
  "tigre",
  "timbre",
  "tirer",
  "tiroir",
  "tissu",
  "titre",
  "toboggan",
  "toilette",
  "toit",
  "tomate",
  "tomber",
  "tonnerre",
  "torchon",
  "tordu",
  "tortue",
  "tôt",
  "toucher",
  "toujours",
  "tour",
  "tourner",
  "tournevis",
  "tousser",
  "tout de suite",
  "tout",
  "toute",
  "tracteur",
  "train",
  "traîneau",
  "traîner",
  "traire",
  "trait",
  "traiter",
  "trampoline",
  "tranche",
  "tranquille",
  "transparent",
  "transpirer",
  "transporter",
  "travail",
  "travailler",
  "travaux",
  "travers",
  "traverser",
  "trembler",
  "tremper",
  "trésor",
  "tricher",
  "tricot",
  "tricoter",
  "tricycle",
  "trier",
  "triste",
  "trois",
  "troisième",
  "tromper",
  "trompette",
  "trop",
  "trottoir",
  "trou",
  "trouer",
  "trous",
  "trousse",
  "trouver",
  "truc",
  "tube",
  "tuer",
  "tulipe",
  "tunnel",
  "tuyau",
  "type",
  "un",
  "uniforme",
  "univers",
  "usé",
  "usine",
  "utiliser",
  "vacances",
  "vache",
  "vague",
  "vaisselle",
  "valise",
  "valoir",
  "vase",
  "véhicule",
  "vélo",
  "vendre",
  "vendredi",
  "venir",
  "vent",
  "venter",
  "ventre",
  "ver",
  "vérité",
  "verre",
  "vers",
  "verser",
  "vert",
  "veste",
  "vêtement",
  "vétérinaire",
  "viande",
  "vide",
  "vider",
  "vieux",
  "village",
  "ville",
  "vin",
  "virage",
  "vis",
  "visage",
  "visiter",
  "vite",
  "vitesse",
  "vitre",
  "vivant",
  "vivre",
  "voile",
  "voir",
  "voisin",
  "voiture",
  "voix",
  "voler",
  "volet",
  "vouloir",
  "voyage",
  "voyager",
  "vrai",
  "w.-c.",
  "wagon",
  "xylophone",
  "yaourt",
  "yeux",
  "zèbre",
  "zéro",
  "zigzag",
  "zoo"
];
